config:
    backup: true
    banner: true
    create: true
    dotpath: dotfiles
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false
dotfiles:
    f_gitconfig:
        src: gitconfig
        dst: ~/.gitconfig
        link: absolute
profiles:
    thinkpad-l14-g1:
        dotfiles:
        -   f_gitconfig
