
---

config:
    backup: true
    banner: true
    create: true
    dotpath: homedir
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    longkey: false
dotfiles:
    f_gitconfig:
        src: gitconfig
        dst: ~/.gitconfig
        link: absolute
    f_gitconfig.author:
        src: gitconfig.author
        dst: ~/.gitconfig.author
        chmod: '664'
profiles:
    thinkpad-l14-g1:
        dotfiles:
            -   f_gitconfig
            -   f_gitconfig.author
