# .bashrc

# Source global definitions:
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment:
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions

# Test `argrelay` config:
cd /home/uvsmtid/repos/argrelay.git/
source /home/uvsmtid/repos/argrelay.git/exe/shell_env.bash
cd - 1> /dev/null

source ~/repos/argrelay.git/exe/shell_env.bash

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"
