# NOTE: uvsmtid: Except this comment, this is the default `~/.bash_profile` from `fedora` 44.
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

# Added by Antigravity CLI installer:
export PATH="/home/uvsmtid/.local/bin:$PATH"

# Added by `rustup`:
. "$HOME/.cargo/env"
