[status]
style = "bold red"
symbol = "x"
format = "[$symbol $status]($style) "
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[git_status]
ahead = "^"
behind = "v"
diverged = "^v"
conflicted = "="
deleted = "x"
renamed = "r"
modified = "!"
staged = "+"
stashed = '\$'
untracked = "?"

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""

[gradle]
symbol = "gradle "

[kotlin]
symbol = "kt "

[python]
symbol = "py "

[java]
symbol = "java "
