
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/uvsmtid/.sdkman"
[[ -s "/home/uvsmtid/.sdkman/bin/sdkman-init.sh" ]] && source "/home/uvsmtid/.sdkman/bin/sdkman-init.sh"
