
export PATH="$HOME/.local/bin:$HOME/.fzf/bin:${PATH}"

# Shared history across concurrent sessions.
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
# write+import history incrementally, share across sessions
setopt SHARE_HISTORY
# append each cmd right away, not just at shell exit
setopt INC_APPEND_HISTORY
# skip dup of immediately previous cmd
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
# save timestamps
setopt EXTENDED_HISTORY

autoload -Uz compinit
compinit

eval "$(starship init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# Set key bindings for `Home` and `End` keys:
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line

# Function to show full path of specified sub-path (or current directory).
lll () {
    for ITEM in "$@"
    do
        FULL_PATH=$(realpath "$ITEM")
        ls --color=auto -ld "$FULL_PATH"
    done
}

# Function to show full path as `lll` + ssh destination.
llll () {
    for ITEM in "$@"
    do
        FULL_PATH=$(realpath "$ITEM")
        echo "$(whoami)@$(hostname):$(ls --color=auto -d "$FULL_PATH")"
    done
}

source <(fzf --zsh)

# Added by Antigravity CLI installer:
export PATH="/home/uvsmtid/.local/bin:$PATH"
