
export PATH="$HOME/.local/bin:$HOME/.fzf/bin:${PATH}"

autoload -Uz compinit
compinit

eval "$(starship init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# Set key bindings for `Home` and `End` keys:
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line

# Function to show full path of specified sub-path (or current directory).
lll () {
    for ITEM in "$@"
    do
        FULL_PATH=$(realpath "$ITEM")
        ls --color=auto -ld "$FULL_PATH"
    done
}

# Function to show full path as `lll` + ssh destination.
llll () {
    for ITEM in "$@"
    do
        FULL_PATH=$(realpath "$ITEM")
        echo "$(whoami)@$(hostname):$(ls --color=auto -d "$FULL_PATH")"
    done
}

source <(fzf --zsh)

# Added by Antigravity CLI installer:
export PATH="/home/uvsmtid/.local/bin:$PATH"
