[build-system]

requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "local_test"
version = "0.0.0"

classifiers = [
    # This package is local and is never published:
    "Private :: Do Not Upload",
]

# FT_84_11_73_28: supported python versions:
requires-python = ">=3.8"

dependencies = [
    "pytest",
    "pre-commit",
    "dotbot",
    "tmuxp",
    "protoprimer @ git+https://github.com/uvsmtid/protoprimer.git@c45a1ec47fee33ba3b431ced7ab2763eb152229c#egg=protoprimer&subdirectory=src/protoprimer",
    "metaprimer @ git+https://github.com/uvsmtid/protoprimer.git@c45a1ec47fee33ba3b431ced7ab2763eb152229c#egg=metaprimer&subdirectory=src/metaprimer",
]

[tool.setuptools.packages.find]
where = ["./main"]

[tool.setuptools.package-dir]
local_test = "./main/local_test"
